apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: group25
      defaultBucket: peak_load
      tlsSkipVerify: true
    secureJsonData:
      token: peak-token-group25
    isDefault: true
